### ISSUE TITLE
LV1 에 대한 스스로 하는 코드 리뷰 입니다.

### ISSUE THREAD

**Issue by totobon6125** [totobon6125/node_hw01#2]
// 게시글 수정 API : PUT
```
router.put("/:_postId", async (req, res) => {
    try {
        const postId = req.params._postId;
        const { password, title, content } = req.body;
        const existingPost = await Post.findOne({ _id: postId });
        if (!existingPost) {
            return res.status(404).json({ message: "게시글 조회에 실패했습니다." });
        }
        const dbPassword = existingPost.password;
        if (dbPassword === password) {
            await Post.updateOne(
                { _id: postId },
                {
                    title,
                    content,
                }
            );
            return res.status(204).json({ message: "게시글을 수정하였습니다." }); // message  가 뜨지 않은 이유는 무엇인가???
        } else {
            return res.status(401).json({ message: "비밀번호가 일치하지 않습니다." });
        }
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: "서버 오류가 발생했습니다." });
    }
});
```

- 주석으로도 적어놨지만 게시글 을 수정하면 db에 수정되어 올라가나 수정되었다는 문구가 뜨지 않습니다. 왜 문구가 안 뜨는지 이유를 모르겠습니다...

- 그 외에도 lv1 을 할 땐 개인적인 사정으로 강의 시청 및 과제를 할 수 있는 시간이 짧아 많이 미흡한 코드를 제출 하게 된 것이 너무 싫습니다. 고칠 점이나 아쉬운 점들을 많이 적어주시면 정말로 감사하겠습니다.

**Comment by diasm3** [comment]
1. 수정된 결과가 안나온 이유는 아래와 같습니다.
- status를 204로 사용하셔서 그렇습니다. 204는 [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) 에 보시면 *no content* 입니다. 기본적으로 204는 아무것도 반환하지 않습니다.
- [stackover flow](https://stackoverflow.com/questions/34087272/http-status-code-for-put)
<img width="1506" alt="image" src="https://github.com/totobon6125/node_hw01/assets/56494905/15bea109-f4ce-4fc9-9b36-561576a18284">
