### ISSUE TITLE
이슈

### ISSUE THREAD

**Issue by diasm3** [totobon6125/node_hw01#3]
1. 500에러처리를 잘하셨습니다. 
2. 코멘트를 작성할때 같은 user id로 코멘트를 생성하면 아래와 같은 에러가 발생합니다. 
- 이 에러는 제 DB에서만 발생하는 에러 일수도 있습니다. 하지만 이런일이 발생 할 수도 있으니 참고 하시면됩니다.
- [스택오버플로우](https://stackoverflow.com/questions/24430220/e11000-duplicate-key-error-index-in-mongodb-mongoose)
- 중복되는 index를 삭제 하면 됩니다.
```bash
MongoServerError: E11000 duplicate key error collection: spa_comments.comments index: user_1 dup key: { user: "hello" }
    at /Users/semyungpark/Documents/dev/hgh16/node_hw01/node_modules/mongodb/lib/operations/insert.js:50:33
    at /Users/semyungpark/Documents/dev/hgh16/node_hw01/node_modules/mongodb/lib/operations/command.js:84:64
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  index: 0,
  code: 11000,
  keyPattern: { user: 1 },
  keyValue: { user: 'hello' },
  [Symbol(errorLabels)]: Set(0) {}
}
``` 
3. 코멘트를 조회/수정/삽입 할때 post Id 체크를 해야합니다.
- post id가 체크가 안된다면 잘못된 postID를 가지고도 comment를 조회, 삭제, 수정을 할 수 있습니다.

**Comment by totobon6125** [comment]
감사합니다~!
